application/modules/order/controllers/OrderController.php
<?php
namespace app\modules\order\controllers;

use yii;
use app\modules\order\models\tools\OrderSearch;
use app\modules\order\models\Order;
use app\modules\order\models\Payment;
use app\modules\order\models\Element;
use app\modules\order\models\tools\ElementSearch;
use app\modules\order\models\Field;
use app\modules\order\models\FieldValue;
use app\modules\order\models\PaymentType;
use app\modules\order\models\ShippingType;
use yii\web\Controller;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\modules\order\events\OrderEvent;

class OrderController  extends Controller
{
    public function behaviors()
    {
        return [
            'adminAccess' => [
                'class' => AccessControl::className(),
				'only' => ['create', 'update', 'index', 'view', 'push-elements', 'print', 'delete', 'editable', 'to-order', 'update-status'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => $this->module->adminRoles,
                    ]
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'push-elements' => ['post'],
                    'to-order' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if ($action->id == 'print' | $action->id == 'create') {
            $this->enableCsrfValidation = false;
        }

        return parent::beforeAction($action);
    }

    public function actionIndex($tab = 'orders')
    {
        $searchModel = new OrderSearch();

        $searchParams = yii::$app->request->queryParams;

        //if(!yii::$app->user->can(current(yii::$app->getModule('order')->adminRoles))) {
        //    $searchParams['OrderSearch']['seller_user_id'] = yii::$app->user->id;
        //}

        $dataProvider = $searchModel->search($searchParams);

        if($tab == 'assigments') {
            $dataProvider->query->andWhere(['order.is_assigment' => '1']);
        } else {
            $dataProvider->query->andWhere('(order.is_assigment IS NULL OR order.is_assigment = 0)');
        }

        if(yii::$app->request->get('time_start')) {
            $dataProvider->query->orderBy('order.timestamp ASC');
        }

        $dataProvider->pagination = ["pageSize" => 100];

        $paymentTypes = ArrayHelper::map(PaymentType::find()->all(), 'id', 'name');
        $shippingTypes = ArrayHelper::map(ShippingType::find()->all(), 'id', 'name');

		$this->getView()->registerJs('oak.orders_list.elementsUrl = "'.Url::toRoute(['/order/tools/ajax-elements-list']).'";');

        return $this->render('index', [
            'tab' => Html::encode($tab),
            'searchModel' => $searchModel,
            'shippingTypes' => $shippingTypes,
            'paymentTypes' => $paymentTypes,
			'module' => $this->module,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionPushElements($id)
    {
        if($model = $this->findModel($id)) {
            yii::$app->order->pushCartElements($id);
        }

        $this->redirect(['/order/order/view', 'id' => $id]);
    }

    public function actionView($id, $push_cart = false)
    {
        $model = $this->findModel($id);

        $searchModel = new ElementSearch;
        $params = yii::$app->request->queryParams;
        if(empty($params['ElementSearch'])) {
            $params = ['ElementSearch' => ['order_id' => $model->id]];
        }

        $dataProvider = $searchModel->search($params);

        $paymentTypes = ArrayHelper::map(PaymentType::find()->all(), 'id', 'name');
        $shippingTypes = ArrayHelper::map(ShippingType::find()->all(), 'id', 'name');

        $fieldFind = Field::find();

        $this->getView()->registerJs('oak.order.outcomingAction = "' . Url::toRoute(['/order/tools/outcoming']) . '";');

        return $this->render('view', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'shippingTypes' => $shippingTypes,
            'fieldFind' => $fieldFind,
            'paymentTypes' => $paymentTypes,
            'model' => $model,
        ]);
    }

    public function actionPrintLast()
    {
        $this->layout = 'print';

        $this->enableCsrfValidation = false;

        $model = Order::find()->orderBy('id DESC')->limit(1)->one();

        $searchModel = new ElementSearch;
        $params = yii::$app->request->queryParams;
        if(empty($params['ElementSearch'])) {
            $params = ['ElementSearch' => ['order_id' => $model->id]];
        }

        $dataProvider = $searchModel->search($params);

        $paymentTypes = ArrayHelper::map(PaymentType::find()->all(), 'id', 'name');
        $shippingTypes = ArrayHelper::map(ShippingType::find()->all(), 'id', 'name');

        $fieldFind = Field::find();

        return $this->render('print', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'shippingTypes' => $shippingTypes,
            'fieldFind' => $fieldFind,
            'paymentTypes' => $paymentTypes,
            'module' => $this->module,
            'model' => $model,
        ]);
    }

    public function actionPrint($id)
    {
        $this->layout = 'print';

        $this->enableCsrfValidation = false;

        $model = $this->findModel($id);
        $searchModel = new ElementSearch;
        $params = yii::$app->request->queryParams;
        if(empty($params['ElementSearch'])) {
            $params = ['ElementSearch' => ['order_id' => $model->id]];
        }

        $dataProvider = $searchModel->search($params);

        $paymentTypes = ArrayHelper::map(PaymentType::find()->all(), 'id', 'name');
        $shippingTypes = ArrayHelper::map(ShippingType::find()->all(), 'id', 'name');

        $fieldFind = Field::find();

        return $this->render('print', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'shippingTypes' => $shippingTypes,
            'fieldFind' => $fieldFind,
            'paymentTypes' => $paymentTypes,
            'module' => $this->module,
            'model' => $model,
        ]);
    }

    public function actionCreate()
    {
        $orderModel = yii::$app->orderModel;

        $model = new $orderModel;

        $this->getView()->registerJs("jQuery('.buy-by-code-input').focus();");

        if ($model->load(yii::$app->request->post()) && $model->save()) {

            if($ordersEmail = yii::$app->getModule('order')->ordersEmail) {
                $sender = yii::$app->getModule('order')->mail
                    ->compose('admin_notification', ['model' => $model])
                    ->setTo($ordersEmail)
                    ->setFrom(yii::$app->getModule('order')->robotEmail)
                    ->setSubject(Yii::t('order', 'New order')." #{$model->id} ({$model->client_name})")
                    ->send();
            }

            $module = $this->module;
            $orderEvent = new OrderEvent(['model' => $model, 'elements' => $model->elements]);
            $this->module->trigger($module::EVENT_ORDER_CREATE, $orderEvent);

            return $this->redirect([$this->module->orderCreateRedirect, 'id' => $model->id]);
        } else {
            //yii::$app->cart->truncate();
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionGetOrderFormLight($useAjax = false)
    {
        return $this->renderAjax('formLight', [
            'useAjax' => $useAjax,
        ]);
    }

    public function actionCreateAjax()
    {
        $orderModel = yii::$app->orderModel;

        $model = new $orderModel;

        if ((yii::$app->has('worksess')) && $session = yii::$app->worksess->soon()) {
            $model->sessionId = $session->id;
        } else {
            $model->sessionId = null;
        }

        $order = yii::$app->request->post('Order');
        if (isset($order['staffer'])) {
            $model->staffer = $order['staffer'];
        }

        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        // $model->staffer = yii::$app->request->post();
        if ($model->load(yii::$app->request->post()) && $model->save()) {
            $model = yii::$app->order->get($model->id);

            if($ordersEmail = yii::$app->getModule('order')->ordersEmail) {
                $sender = yii::$app->getModule('order')->mail
                    ->compose('admin_notification', ['model' => $model])
                    ->setTo($ordersEmail)
                    ->setFrom(yii::$app->getModule('order')->robotEmail)
                    ->setSubject(Yii::t('order', 'New order')." #{$model->id} ({$model->client_name})")
                    ->send();
            }

            $module = $this->module;
            $orderEvent = new OrderEvent(['model' => $model, 'elements' => $model->elements]);
            $this->module->trigger($module::EVENT_ORDER_CREATE, $orderEvent);

            $nextStepAction = false;

            // создаём заказ, очищаем информер корзины
            if ($model->cost == 0) {
                return [
                    'status' => 'success',
                    'nextStep' => $nextStepAction
                ];
            }

            // создаём заказ, отдаём урл на рендер формы оплаты
            if (\yii::$app->getModule('order')->paymentFormAction) {
                $nextStepAction = Url::to([\yii::$app->getModule('order')->paymentFormAction , 'id' => $model->id, 'useAjax' => 1]);
            }

            if ($this->module->paymentFreeTypeIds && in_array($model->payment_type_id, $this->module->paymentFreeTypeIds)) {
                \Yii::$app->order->setStatus($model->id, 'payed');
            }

application/modules/order/controllers/ToolsController.php
<?php
namespace app\modules\order\controllers;

use yii;
use yii\web\Controller;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use app\modules\cart\widgets\ElementsList;
use app\modules\cart\widgets\CartInformer;
use app\modules\order\models\ShippingType;
use app\modules\order\events\OrderEvent;

class ToolsController  extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
				'only' => ['user-info', 'ajax-elements-list', 'outcoming', 'find-users-window', 'user-info'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => $this->module->adminRoles,
                    ]
                ]
            ],
        ];
    }

    public function actionFindUsersWindow()
    {
        $this->layout = '@vendor/pistol88/yii2-order/views/layouts/mini';

        $searchModel = new $this->module->userSearchModel;
        $model = new $this->module->userModel;

        $dataProvider = $searchModel->search(yii::$app->request->queryParams);

        return $this->render('users_list', [
            'searchModel' => $searchModel,
            'model' => $model,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionFindProductsWindow()
    {
        $this->layout = '@vendor/pistol88/yii2-order/views/layouts/mini';

        $searchModel = new $this->module->productSearchModel;
        $model = new $this->module->productModel;
        $categories = $this->module->productCategoriesList;

        $dataProvider = $searchModel->search(yii::$app->request->queryParams);

        return $this->render('products_list', [
            'categories' => $categories,
            'searchModel' => $searchModel,
            'model' => $model,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionBuyProductByCode()
    {
        $code = yii::$app->request->post('code');

        $model = new $this->module->productModel;

        if($model = $model::find()->where('code=:code OR id=:code', [':code' => $code])->one()) {
            yii::$app->cart->put($model->sellModel, 1, []);

            $json = ['status' => 'success'];
        } else {
            $json = [
                'status' => 'fail',
                'message' => yii::t('order', 'Not found')
            ];
        }

        die(json_encode($json));
    }

    public function actionUserInfo()
    {
        $userId = yii::$app->request->post('userId');

        $model = new $this->module->userModel;

        if($userId) {
            $userModel = $model::find()->where(['id' => $userId])->one();
        } else {
            die([
                'status' => 'fail',
                'message' => yii::t('order', 'Not found')
            ]);
        }

        $promocode = false;

        if(!$userModel) {
            foreach($this->module->userModelCustomFields as $field) {
                if($userModel = $model::find()->where([$field => $userId])->one()) {
                    break;
                }
            }
        }

        if($userModel->promocode) {
            $promocode = $userModel->promocode;
        }

        if($userModel) {
            $fullName = $userModel->name;

            $json = [
                'id' => $userModel->id,
                'status' => 'success',
                'promocode' => $promocode,
                'username' => $userModel->username,
                'email' => $userModel->email,
                'phone' => $userModel->phone,
                'client_name' => $fullName,
            ];
        } else {
            $json = [
                'status' => 'fail',
                'message' => yii::t('order', 'Not found')
            ];
        }

        die(json_encode($json));
    }

	public function actionAjaxElementsList()
	{
		$model = yii::$app->order->get(yii::$app->request->post('orderId'));

		$elements = Html::ul($model->elements, ['item' => function($item, $index) {
			return Html::tag(
				'li',
				"{$item->getModel()->getCartName()} - {$item->base_price} {$this->module->currency}x{$item->count}",
				['class' => 'post']
			);
		}]);

        die(json_encode([
            'elementsHtml' => $elements,
        ]));
	}

    public function actionCartInfo()
    {
        die(json_encode([
            'cart' => ElementsList::widget(['type' => ElementsList::TYPE_FULL, 'showOffer' => false, 'otherFields' => $this->module->cartCustomFields]),
            'total' => CartInformer::widget(['htmlTag' => 'div', 'text' => '{c} на {p}']),
            'count' => yii::$app->cart->count,
        ]));
    }

    public function actionUpdateShippingType()
    {
        $shippingTypeId = (int)yii::$app->request->post('shipping_type_id');
        yii::$app->session->set('orderShippingType', $shippingTypeId);

        die(json_encode([
            'total' => yii::$app->cart->cost,
        ]));
    }

    public function actionOneClick()
    {
        $orderModel = yii::$app->orderModel;

        $model = new $orderModel;

        $elementModel = yii::$app->request->post('model');
        $elementModel = new $elementModel;

        $elementId = yii::$app->request->post('id');

        if($elementModel = $elementModel::findOne($elementId)) {
            yii::$app->cart->put($elementModel, 1, []);

            if ($model->load(yii::$app->request->post()) && $model->save()) {
                if($ordersEmail = yii::$app->getModule('order')->ordersEmail) {
                    $sender = yii::$app->getModule('order')->mail
                        ->compose('admin_notification', ['model' => $model])
                        ->setTo($ordersEmail)
                        ->setFrom(yii::$app->getModule('order')->robotEmail)
                        ->setSubject(Yii::t('order', 'New order')." #{$model->id} ({$model->client_name})")
                        ->send();
                }

                $module = $this->module;
                $orderEvent = new OrderEvent(['model' => $model]);
                $this->module->trigger($module::EVENT_ORDER_CREATE, $orderEvent);

                $module = $this->module;
                $orderEvent = new OrderEvent(['model' => $model]);
                $this->module->trigger($module::EVENT_ORDER_CREATE, $orderEvent);

                $json = ['id' => $model->id, 'redirect' => Url::toRoute([$this->module->successUrl, 'id' => $model->id, 'payment' => $model->payment_type_id]), 'result' => 'success'];
            } else {
                //yii::$app->cart->truncate();
                $json = ['result' => 'fail'];
                $json['error'] = current($model->getFirstErrors());
            }

            die(json_encode($json));
        }
    }

	public function actionOutcoming()
	{
		$stockId = yii::$app->request->post('stock_id');
        $productId = yii::$app->request->post('product_id');
        $count = yii::$app->request->post('count');
        $orderId = yii::$app->request->post('order_id');

        $json = ['result' => 'fail'];

        if($stockId && $productId && $count && yii::$app->has('stock')) {
            $stock = yii::$app->stock;

            $amount = $stock->outcoming($stockId, $productId, $count, $orderId);

            $json['amount'] = $amount;
            $json['result'] = 'success';
        }

        die(json_encode($json));
	}
}

application/modules/order/views/order/_form.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\modules\order\models\PaymentType;
use app\modules\order\models\ShippingType;
use app\modules\cart\widgets\ElementsList;
use app\modules\cart\widgets\CartInformer;
use app\modules\order\models\FieldValue;

$paymentTypes = ArrayHelper::map(PaymentType::find()->orderBy('order DESC')->all(), 'id', 'name');
$shippingTypes = ArrayHelper::map(ShippingType::find()->orderBy('order DESC')->all(), 'id', 'name');

app\modules\order\assets\CreateOrderAsset::register($this);
$this->registerJs("oak.createorder.updateCartUrl = '".Url::toRoute(['tools/cart-info'])."';");
?>

<div class="order-form">

    <?php $form = ActiveForm::begin(); ?>
        <div class="row">
            <div class="col-lg-6">
                <div class=" panel panel-default">
                    <div class="panel-heading"><h3><?=yii::t('order', 'Order');?></h3></div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-6">
                                <?= $form->field($model, 'status')->dropDownList(Yii::$app->getModule('order')->orderStatuses) ?>
                            </div>
                            <div class="col-lg-6">
                                <?= $form->field($model, 'date')->textInput(['value' => date('Y-m-d H:i:s')]) ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <?= $form->field($model, 'shipping_type_id')->dropDownList($shippingTypes) ?>
                            </div>
                            <div class="col-lg-6">
                                <?= $form->field($model, 'payment_type_id')->dropDownList($paymentTypes) ?>
                            </div>
                        </div>

                        <?= $form->field($model, 'comment')->textArea(['maxlength' => true]) ?>
                    </div>
                </div>
                <div class=" panel panel-default">
                   <div class="panel-heading"><h3>Клиент</h3></div>
                   <div class="panel-body">
                       <div class="row">
                           <div class="col-lg-6">
                               <?= $form->field($model, 'user_id')->textInput(['id' => 'choose-user-id', 'data-info-service' => Url::toRoute(['tools/user-info']), 'data-toggle' => "modal", 'data-target' => "#usersModal"]) ?>

                               <?= $form->field($model, 'client_name')->textInput(['maxlength' => true]) ?>

                               <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>

                               <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

                           </div>
                       </div>
                   </div>
               </div>
            </div>
            <div class="col-lg-6">
                <div class=" panel panel-default">
                    <div class="panel-body">
                        <div class="form-group offer">
                            <?= Html::submitButton($model->isNewRecord ? Yii::t('order', 'Create order') : Yii::t('order', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php ActiveForm::end(); ?>
</div>

application/modules/order/views/order/create.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\modules\order\models\PaymentType;
use app\modules\order\models\ShippingType;
use app\modules\cart\widgets\ElementsList;
use app\modules\cart\widgets\CartInformer;
use app\modules\order\widgets\BuyByCode;
use app\modules\order\widgets\ChooseClient;
use app\modules\order\models\FieldValue;

$paymentTypes = ArrayHelper::map(PaymentType::find()->orderBy('order DESC')->all(), 'id', 'name');
$shippingTypes = ArrayHelper::map(ShippingType::find()->orderBy('order DESC')->all(), 'id', 'name');

app\modules\order\assets\CreateOrderAsset::register($this);
$this->registerJs("oak.createorder.updateCartUrl = '".Url::toRoute(['tools/cart-info'])."';");

$this->title = Yii::t('order', 'Create order');
$this->params['breadcrumbs'][] = ['label' => Yii::t('order', 'Orders'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-create">

<div class="order-form">
    <div class="row">
        <?php $form = ActiveForm::begin(['id' => 'orderForm']); ?>
        <div class="col-lg-6">
            <div class=" panel panel-default">
                <div class="panel-heading"><h3>Заказ</h3></div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-6">
                            <?= $form->field($model, 'status')->dropDownList(Yii::$app->getModule('order')->orderStatuses) ?>
                        </div>
                        <div class="col-lg-6">
                            <?= $form->field($model, 'date')->textInput(['value' => date('Y-m-d H:i:s')]) ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <?= $form->field($model, 'shipping_type_id')->dropDownList($shippingTypes) ?>
                        </div>
                        <div class="col-lg-6">
                            <?= $form->field($model, 'payment_type_id')->dropDownList($paymentTypes) ?>
                        </div>
                    </div>

                    <?php if($fields = $model->allfields) { ?>
                        <div class="row">
                            <?php foreach($fields as $fieldModel) { ?>
                                <div class="col-lg-12 col-xs-12">
                                    <?php
                                    if($widget = $fieldModel->type->widget) {
                                        echo $widget::widget(['form' => $form, 'fieldModel' => $fieldModel]);
                                    }
                                    else {
                                        echo $form->field(new FieldValue, 'value['.$fieldModel->id.']')->label($fieldModel->name)->textInput(['required' => ($fieldModel->required == 'yes')]);
                                    }
                                    ?>
                                    <?php if($fieldModel->description) { ?>
                                        <p><small><?=$fieldModel->description;?></small></p>
                                    <?php } ?>
                                </div>
                            <?php } ?>
                        </div>
                    <?php } ?>

                    <?= $form->field($model, 'comment')->textArea(['maxlength' => true]) ?>
                </div>
            </div>
            <div class=" panel panel-default">
               <div class="panel-heading"><h3>Клиент</h3></div>
               <div class="panel-body">
                   <?=ChooseClient::widget(['form' => $form, 'model' => $model]);?>
               </div>

           </div>
        </div>
        <?php ActiveForm::end(); ?>
        <div class="col-lg-6">
            <div class=" panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-lg-9">
                            <h3>Состав</h3>
                        </div>
                        <div class="col-lg-3">
                            <a href="#productsModal" data-toggle="modal" data-target="#productsModal" class="choice-product btn "><?=yii::t('order', 'Choose');?>... <span class="glyphicon glyphicon-plus add-option"></span></a>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="cart">
                        <?=ElementsList::widget(['type' => ElementsList::TYPE_FULL, 'showOffer' => false, 'otherFields' => yii::$app->getModule('order')->cartCustomFields]);?>
                    </div>
                    <?=BuyByCode::widget();?>
                </div>
            </div>

            <?php if(yii::$app->has('promocode')) { ?>
                <div class=" panel panel-default">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-lg-9">
                                <h3>Промокод</h3>
                            </div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="form-group promocode">
                            <?=\pistol88\promocode\widgets\Enter::widget();?>
                        </div>
                    </div>
                </div>
            <?php } ?>

            <div class=" panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-lg-9">
                            <h3>Итого</h3>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="total">
                        <?= CartInformer::widget(['htmlTag' => 'div', 'text' => '{c} на {p}']); ?>
                    </div>
                    <div class="form-group offer">
                        <?= Html::submitButton($model->isNewRecord ? Yii::t('order', 'Create order') : Yii::t('order', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary', 'onclick' => '$("#orderForm").submit();']) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="productsModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><?=yii::t('order', 'Products');?></h4>
      </div>
      <div class="modal-body">
        <iframe src="<?=Url::toRoute(['tools/find-products-window']);?>" id="products-list-window"></iframe>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><?=yii::t('order', 'Close');?></button>
      </div>
    </div>
  </div>
</div>


</div>

application/modules/order/views/order/formLight.php
<div class="custom-order-form-light-container" style="max-width: 320px;">
    <?php if (Yii::$app->service->splitOrderPerfome) {
            if (isset(yii::$app->worksess->soon()->users)) {
                $staffers = yii::$app->worksess->soon()->getUsers();
                $staffers = $staffers->all();
            } else {
                $staffers = null;
            }
        } else {
            $staffers = null;
        }
    ?>

    <?= \app\modules\order\widgets\OrderFormLight::widget([
        'useAjax' => $useAjax,
        'staffer' => $staffers
    ]); ?>
</div>

application/modules/order/views/order/update.php
<?php

use yii\helpers\Html;

$this->title = Yii::t('order', 'Update order');
$this->params['breadcrumbs'][] = ['label' => Yii::t('order', 'Orders'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('order', 'Update');
?>
<div class="order-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>